#!/bin/bash
#shell function demo
foo=0
func_1(){
	local foo # variable foo local to func1
	foo=1
	echo "func1: foo = $foo"
	}
func_2(){
    local foo # variable foo local to func1
    foo=2
    echo "func2: foo = $foo"
    }
echo "global : foo = $foo"
func_1
echo "global : foo = $foo"
func_2
echo "global : foo = $foo"
