#!/bin/bash
MIN=1
MAX=100
INT=50

if [[ "$INT" =~ ^-?[0-9]+$ ]]; then
	if [[ INT -ge $MIN && $INT -le MAX ]]; then
		echo "$INT is within $MIN to $MAX."
	else
		echo "$INT is out of range"
	fi
else 
	echo "$INT is not an integer." >&2
	exit 1
fi

