#!/bin/bash
echo -n "Please enter an integer"
read int

if [[ "$int" =~ ^-?[0-9]+$ ]]; then
	if [ $int -eq 0 ]; then
		echo "$int is zero."
	else
	echo "$int is not zero"
	fi
else 
	echo "Input value is not an integer." >&2
	exit 1
fi
